### ISSUE TITLE
July 22 at 1 PM: Introduction to machine learning

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/meetup#1]
Hi everyone! 

On Friday July 22 at 1:00 PM in SEEC (room TBD) we'll meet and work on the material for week 1 in Andrew Ng's machine learning course on Coursera. This covers linear regression and has a little review of linear algebra. Feel free to work out implementations in the programming language of your choice - and even better if you find a way to integrate this with some of your current Earth Lab projects! I'll also spend a bit of time to show how we can use GitHub to coordinate this group. 

You can use this issue as a discussion forum about the event. So, any questions can go here (about the group, the content of the course, meaning of life etc.).

See you Friday!

**Comment by tshrum** [comment]
**Protip**: If Prof. Andrew Ng talks a bit too slow or too fast for your liking, click on the settings wheel on the video and you can change the speed.

**Comment by mbjoseph** [comment]
Good tip! Also feel free to share your solutions. I'll be curious to see what people come up with. Here is my attempt: http://nbviewer.jupyter.org/github/mbjoseph/python_ml/blob/master/regression/grdesc_fns.ipynb

**Comment by tshrum** [comment]
I thought that assignment was for week 2? Are you overachieving or am I behind?

**Comment by mbjoseph** [comment]
It's not an assignment - I just wanted to work out an implementation on my own. At least for me, implementing the math in a program helps me understand what's going on. AFAIK there was no homework.
