### ISSUE TITLE
Sep 16: web scraping extravaganza

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/meetup#13]
Sep 16 from 1 - 2 PM in SEEC S372 we'll talk about web scraping. I'll show how I wrangled millions of cattle sales from the USDA, and we may also talk about some other applications (e.g., scraping basketball stats, or news articles).

**Comment by MollieBuck** [comment]
Here are the Python scraping and parsing codes with a .csv file to use. 
https://gist.github.com/MollieBuck/9c448c4bdfb127b63764e3e2f778c777

**NOTE** You will need to download Chromedriver for the script to work. Download it at https://sites.google.com/a/chromium.org/chromedriver/

**Comment by mbjoseph** [comment]
Thanks Mollie! Here's a link to the AMS scraping repo: https://github.com/mbjoseph/ams-wrangler

**Comment by lwasser** [comment]
This was great guys. I learned a bunch!!
