### ISSUE TITLE
Sep 23: mapmaking woes in R and elsewhere

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/meetup#14]
On Friday Nate will present to us on a recent figure that he made, along with live commentary on the woes resulting from an attempted R implementation. 

Where: SEEC S372
When: 1-2 PM

**Comment by NateMietk** [comment]
Hi all,

Thanks for joining us today for the data jam!  It was great to talk to you about this work and have such a rich dialogue throughout the talk. To follow up on the data used in the figures please see the following links.

Geomac: http://rmgsc.cr.usgs.gov/outgoing/GeoMAC/

MTBS: http://www.mtbs.gov/dataaccess.html

FACTS: http://data.fs.usda.gov/geodata/edw/datasets.php

GAP Land Cover: http://gapanalysis.usgs.gov/gaplandcover/data/download/


Best,
Nate
