### ISSUE TITLE
Oct 7: Python data science tour

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/meetup#16]
On Oct 7 Ben Kamphaus will be presenting a tour of the Python data science ecosystem. Here's what to expect: http://benkampha.us/2016-09-12.html

To check out some of the materials ahead of time see: https://github.com/benkamphaus/python-datasci-tour

What: Introduction to the Python data science ecosystem
Where: SEEC S372
When: Oct 7, 1 -2 PM

**Comment by benkamphaus** [comment]
Time allowing, I am planning on showing/giving a TensorFlow demo. Installing TensorFlow can be kind of a pain, so I've [provided a Dockerfile template repo](https://github.com/benkamphaus/tensorflow-docker-template) that shows how to use docker to execute TensorFlow programs on either the CPU or GPU (in which case you'd use [nvidia-docker](https://github.com/NVIDIA/nvidia-docker)). Following along isn't necessary, but if you want to then using docker to manage configuration for libraries with architecture-specific native dependencies (like TensorFlow) is much simpler.

**Comment by benkamphaus** [comment]
Jupyter notebook themes: https://github.com/dunovank/jupyter-themes

**Comment by lwasser** [comment]
hey @mbjoseph -- bummed i missed this - looks like a cool session! have you consider using the WIKI to store links, etc associated with these for a more visible permanent documentation of resources associated with the meetup? Just a thought. excited to check out the jupyter themes!! :) then you don't have to close issues with cool content in them. :)

**Comment by mbjoseph** [comment]
Sorry you missed it! I have not considered a Wiki, but if you want to start one feel free!

**Comment by mjc87** [comment]
@mbjoseph and @lwasser - As an outside observer, I'd vote against using the Wiki as changes to GitHub wikis aren't sent in email notifications to repo followers afaik. Both PRs and Issues do come through if someone is watching, so perhaps creating a directory or page that is modified by PR in this or another repo would be a better idea that using a wiki? That way anyone watching your group gets notifications of events and materials? Or am I missing some other notification avenue that already exists?

**Comment by lwasser** [comment]
Sure – I think whatever mechanism to store information over time in a visible way, works for me. The issue I see now is issues get closed with lots of good stuff in them! Just a thought.
