### ISSUE TITLE
Dec 09: bug hunt, Jekyll, and the new Earth Lab website

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/meetup#23]
Leah and Max have been working on a website for Earth Lab's dynamic content. We've done a soft release (https://earthlab.github.io), but we need your help identifying bugs! Please join us Friday to see what we've put together, and help us make the site better.

When: Friday, Dec 9, 2016, 1 - 2 PM
Where: SEEC S372

**Comment by lwasser** [comment]
Please come and give us feedback! Try to break the website – we challenge you ☺
This website is going to be the face of our earth lab resources – it needs to be awesome!

If you can’t make it, email us OR better yet --- submit git issues!!
Thanks, all!
Leah

**Comment by lwasser** [comment]
Hey all -- please think about a URL that would be good for the earth lab site! We will brainstorm some tomorrow. Also think about things you'd like to see on the site https://earthlab.github.io in the future!!

See you all tomorrow. 
leah
