### ISSUE TITLE
2017-02-24: Cheetah scraping with Selenium

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/meetup#27]
This Friday Lise St. Denis is going to talk about a script she's working on that uses Selenium to crawl and scrape Cheetah reports (incident resource summaries) from the National Incident Management System Incident Command System historical web site. 

What: Web scraping!
Who: Lise St. Denis
Where: SEEC S372
When: 2017-02-22, 2 - 3 PM

**Comment by lisestdenis** [comment]
Here are three code examples 
part 1: creating a browser window and selecting urls
part 2: navigating within cheetah reports page and selecting each report
CheetahScraperv2.py: using incident data to crawl and scrape NIMS/ICS Cheetah reports 2003-2013
