### ISSUE TITLE
Earth Lab Incubator: Earth Lab Learn How to Setup a Python (Anaconda) Environment, Monday 7/16, 11:00am-12:00pm, SEEC S372

### ISSUE THREAD

**Issue by abraswell** [earthlab/meetup#49]
Earth Lab invites you to short workshop where you will learn how to setup a Python Environment using the Anaconda Python distribution.
When: July 16th from 11am-12pm
Where: SEEC S372

Python is notoriously tricky to setup. Further, often packages that you may need to use can conflict with one another. One solution to dealing with tricky installations is to use or create pre-built environments that contain all of the packages that you need to install in one place. Since the instructions to build these environments are pre-defined, you can easily use this environment on different computers or even in the cloud as a part of a contained environment. In this workshop you will learn how to:

1.     Use Bash / Shell to setup an predefined Anaconda environment

2.     View and activate different Python Anaconda environments

3.     Launch Jupyter Notebook and use the environment of your choice

This workshop is both an opportunity for you to learn the basics of Python environments and learn a bit of Bash. It also is a chance for Earth Lab to test a new environment that it has created to support working with scientific data. We need your help in the form of feedback on how our installation works on different machines!!

What you will need:
·        A laptop with the Anaconda Python 3.x installed and bash installed. Instructions for Windows/Mac/Linux users to install Anaconda and Bash are here.
o   You  need to install bash in addition to anaconda if you use Windows
·        No previous programming experience is required to attend this workshop

The workshop is a part of the weekly Earth Lab Incubator events. Earth Lab Incubator is a meetup (open to all) to foster discussion of new ideas, technical solutions and form collaborations (visit https://github.com/earthlab/meetup to sign up for future events). This workshop will be led by Dr. Leah Wasser (Director of Earth Analytics Education) and Dr. Jenny Palomino (Earth Analytics Instructor).

To register please RSVP using this form (https://docs.google.com/forms/d/14y6yXtw3SxBiExGp8tUbjT8Ke504cAiO-zH97N5DBW4/edit) by midnight on Sunday 7/15. If you RSVP please plan to attend the workshop. If you are no longer able to come, please email earth.lab@colorado.edu prior to the event. The workshop is open to all CU Boulder students, faculty and staff. Please feel free to distribute this invitation to your colleagues.

Thanks,

Earth Lab, University of Colorado Boulder
earth.lab@colorado.edu
S347 SEEC
Phone: (303) 735-6119

**Comment by lwasser** [comment]
Because the group is so small and zoom almost never works in that room, I wasn’t planning to set it up. We only have 1 hour and it’s another thing to manage so if it fails, I’m out of time! However Anna if you’d like to set something up (if that is something you normally do), please do so.

**Comment by abraswell** [comment]
Hey Guys! We have not been setting up zoom since that room went into a tail spin a couple of months ago. Happy to set up a link and then we could just share Leah's screen and audio from her computer? Link below, let me know if that doesn't work for you guys! Thanks!
 
Hi there, 

Anna Braswell is inviting you to a scheduled Zoom meeting. 

Topic: Anna Braswell's Zoom Meeting
Time: Jul 16, 2018 11:00 AM Mountain Time (US and Canada)

Join from PC, Mac, Linux, iOS or Android: https://cuboulder.zoom.us/j/252956996

Or iPhone one-tap :
    US: +16465588656,,252956996#  or +16699006833,,252956996# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 646 558 8656  or +1 669 900 6833 
    Meeting ID: 252 956 996
    International numbers available: https://zoom.us/u/dpTZaqdTi

Or an H.323/SIP room system:
    H.323: 
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 252 956 996

    SIP: 252956996@zoomcrc.com

**Comment by lwasser** [comment]
Thank you Anna.

Sure I’ll happily share it from my computer. It’s a shame that it doesn’t work in that room.

Leah

**Comment by mbjoseph** [comment]
Thanks! The blue snowball + screen share is probably sufficient if you wanted to mic up.

**Comment by abraswell** [comment]
K! Will get the snowball!
