### ISSUE TITLE
Earth Lab Incubator Nov. 30th - Imtiaz Rangwala

### ISSUE THREAD

**Issue by abraswell** [earthlab/meetup#60]
Hi Everyone and Welcome back!

     This week Imtiaz Rangwala of the North Central Climate Adaptation Science Center will be presenting on - EDDI and LERI: An emerging tale of two drought indices (see description below). Please join us at 1 pm on Friday, November 30th in S372!

      -Anna 

EDDI and LERI: An emerging tale of two drought indices

I will introduce two drought indices - Evaporative Demand Drought Index (EDDI) and Landscape Evaporative Response Index (LERI) - that the NC CASC has been involved in developing and using them as experimental guidance tools for drought early warning. I will discuss the current challenges with drought early warning, and how incorporating our understanding of the coupled atmosphere-land surface state through evaporative dynamics could help in strengthen our situational awareness of drought stages and improve the approach to drought early warning.

**Comment by tsan15** [comment]
Hi Anna, This will be my first meetup.  What building are they held in?

Thanks, Todd

**Comment by abraswell** [comment]
Hi Todd!
    There are in SEEC (4001 Discovery Drive). The room (S372) is on the third floor with the rooms marked Earth Lab (south side). Let me know if you have any questions!
    -Anna

**Comment by tsan15** [comment]
Thanks, Anna!
