### ISSUE TITLE
 2019-02-15: hurricane track prediction using deep learning

### ISSUE THREAD

**Issue by sophiegif** [earthlab/meetup#70]
Hi, I will present my recent work on hurricane trajectory prediction.
The forecast of hurricane trajectories is crucial for the protection of people and property, but machine learning techniques have been scarce for this so far. I will present a method that we developed recently, a fusion of neural networks, that is able to combine past trajectory data and reanalysis atmospheric images (wind and pressure 3D fields).  Our network is trained to estimate the longitude and latitude displacement of hurricanes and depressions from a large database from both hemispheres (more than 3000 storms since 1979, sampled at a 6 hour frequency). Finally, I will give an overview of the hackathon that I organized on a very close topic at the Climate Informatics Workshop in September.

**Comment by abraswell** [comment]
Hope you all will join us for Sophie's presentation! We will be meeting at 1 pm on Friday, February 15th, 2018 in SEEC S372.

**Comment by abraswell** [comment]
Hi Everyone!
   For those who were asking, Sophie's email is: sophie.giffard@colorado.edu
   Thanks!
   -Anna
