### ISSUE TITLE
March 22, 2019: Machine Learning Approaches to Prediction of Indian Summer Monsoon

### ISSUE THREAD

**Issue by moumitasaha2018** [earthlab/meetup#74]
Hi all,

I will be presenting my work on prediction of Indian summer monsoon using machine learning approaches.
Indian summer monsoon is a complex climatic phenomenon with variability and
uncertainty involved. India being an agricultural country, monsoon governs the economy of the country and also serves as the source of hydroelectricity power generation, fresh-water renewal, and nourishes flora and fauna of the sub-continent.  I will focus the talk on two major directions-- (a) improving the prediction model for monsoon, (b) identifying new predictors influencing the summer monsoon of the country.  I will be discussing clustering based method for improving the monsoon prediction with ensemble model and next  will focus on some climate network and deep learning methods for identifying new predictors of monsoon and verifying their efficiency in prediction of monsoon at lead.

Hope to see you all!!!!

Regards,
Moumita

**Comment by abraswell** [comment]
Hi everyone!
    Incubator this week will be at 1 pm in SEEC S372 on March 22nd. Hope you can join us!
    -Anna
