### ISSUE TITLE
 Next Earth Lab deep learning meetup: Friday, March 6, 2020 11-noon

### ISSUE THREAD

**Issue by mikoontz** [earthlab/meetup#87]
Dear Deep Learnéd colleagues,

Our next weekly meetup will be next Friday, March 6, 2020 from 11 to noon in SEEC C325 (same room that we've met twice). I've reserved this room at this time slot through the May 22, so we can plan to meet there each week.

For next week, please work through the Stochastic Gradient Descent (SGD) section of Lesson 2. It will likely take a minimum of 2 hours. That is covered in the final ~30 minutes of the [Lesson 2 video](https://course.fast.ai/videos/?lesson=2) and the [second Lesson 2 notebook](https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson2-sgd.ipynb).

Max Joseph will lead us through the lesson. If there is time, we can preview Lesson 3.

If you have any specific questions about getting everything set up and working, feel free to add a comment to this issue and we can crowd source a solution.

Remember the resources folder (collaborative notes and relevant papers) is on Google Drive [here](https://drive.google.com/open?id=1PLrND4qQWcdM3L1gM_UJ6drqJ6kCHyB4). I just added the "Deep double descent" preprint to the `papers` folder. (Also [here](https://arxiv.org/abs/1912.02292)).

See you Friday, March 6th in SEEC C325 or at https://cuboulder.zoom.us/j/2375826693 at 11am!

**Comment by mbjoseph** [comment]
Hey y'all - just a reminder that this is happening today. It's going to be fun!

**Comment by maxwellCcook** [comment]
Hi All - I will be tuning in via Zoom. "See" you at 11!

**Comment by vscholl** [comment]
If anyone is interested joining the "Earth Lab" team for the IDTreeS competition, send me an email today (if you haven't already): victoria.scholl@colorado.edu

More info: https://idtrees.org/

-Victoria

**Comment by mbjoseph** [comment]
Thanks all for the great discussion today! Here's the notebook we went over, with some additional resources at the end: https://gist.github.com/mbjoseph/f19341c8e1357549d52bfdbbc4a0c595
