### ISSUE TITLE
earthlab all hands meeting conflict 3/13/2020

### ISSUE THREAD

**Issue by joemcglinchy** [earthlab/meetup#89]
Hi All, I see that we have an earth lab all-hands meeting this friday at the same time as the fast ai meetup. Anyone feel like meeting earlier, later, or a different day?

**Comment by vscholl** [comment]
Ah, good point - I can't do earlier this particular Friday. I could do later in the afternoon. Or postponing until the following week could work too. Open to other ideas as well...

**Comment by annaspiers** [comment]
Last time the all-hands meeting conflicted, we just skipped that week. In
the case that it's challenging to find another agreeable time, we could try
for two notebooks next week. Also happy to keep the load light and stick to
the first notebook

My availability for Friday after the all-hands is 12-1and 2:30-3:30.

**Comment by mbjoseph** [comment]
I'd recommend we skip this Friday and meet the following week. Many of us will be tied up Friday afternoon with Twensday stuff anyway!
