### ISSUE TITLE
Next Earth Lab deep learning meetup tentatively scheduled for Friday, March 27, 2020 from 11-12

### ISSUE THREAD

**Issue by mikoontz** [earthlab/meetup#91]
Hi deep learners,

We are tentatively scheduling our next deep learning meetup for one week from tomorrow-- March 27, 2020 from 11-12. There will only be a virtual meeting (no in-person meeting) at the usual Zoom link: [https://cuboulder.zoom.us/j/2375826693](https://cuboulder.zoom.us/j/2375826693)

If you find this meetup to be a sustaining and positively distracting experience, please join us! If this is draining in any way, please save your energy and time for your well-being and that of your loved ones. We will see you when you are up for it!

Please work through Lesson 3. There is a lot in this lesson!
The videos start here: [https://course.fast.ai/videos/?lesson=3](https://course.fast.ai/videos/?lesson=3)
There are 4 (!) notebooks to work though:
[lesson3-planet.ipynb](https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-planet.ipynb)
[lesson3-camvid.ipynb](https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-camvid.ipynb)
[lesson3-imdb.ipynb](https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-imdb.ipynb)
[lesson3-head-pose.ipynb](https://nbviewer.jupyter.org/github/fastai/course-v3/blob/master/nbs/dl1/lesson3-head-pose.ipynb
)

Remember the resources folder (collaborative notes and relevant papers) is on Google Drive here: [https://drive.google.com/open?id=1PLrND4qQWcdM3L1gM_UJ6drqJ6kCHyB4](https://drive.google.com/open?id=1PLrND4qQWcdM3L1gM_UJ6drqJ6kCHyB4)

See you Friday, March 20th at [https://cuboulder.zoom.us/j/2375826693](https://cuboulder.zoom.us/j/2375826693) at 11am!

For some conversation around challenges with Lesson 3, see this other issue: [https://github.com/earthlab/meetup/issues/88](https://github.com/earthlab/meetup/issues/88).

**Comment by mbjoseph** [comment]
We ended up deciding not to meet today, and instead to meet one week later. See #88 for details.
