### ISSUE TITLE
Next Earth Lab Deep Learning Meetup - 6/19/2020 11am-12pm MST

### ISSUE THREAD

**Issue by joemcglinchy** [earthlab/meetup#98]
Hello,

I know we don't have an agreed upon course to work through just yet, but if any are interested I am happy to go over two use cases I've come across in my own work using Pytorch. The Zoom link is in the google doc or slack channel.

The use cases are:

* Satellite image chip classification (fast.ai)
    * RGB Basemap tiles
    * Resnet classifier
* Binary segmentation of complex surfaces (pytorch + torchsat)
    * Unet with resnet encoder

**Comment by Chathu84** [comment]
@joemcglinchy Thanks Joe. I'm in.

**Comment by joemcglinchy** [comment]
sorry all, i typo'd the date. This meet up is for *today*, 6/19/2020
